### ISSUE TITLE
Update website overall design

### ISSUE THREAD

**Issue by Yndira-E** [FlowFuse/website#1654]
### Description

In pursuit of a more professional appearance that aligns with the brand attributes outlined in [this document](https://docs.google.com/document/d/18iVokiP3eHqOphvQ5zinau_kFnNevLlrHTp9F3M0NWM/edit?usp=sharing), and taking into consideration our [design inspiration websites](https://flowfuse.com/handbook/design/#inspiration), we'll implement layout and color scheme changes to the website..

```[tasklist]
### Tasks
- [ ] https://github.com/FlowFuse/website/issues/1672
- [ ] https://github.com/FlowFuse/website/issues/1656
- [ ] https://github.com/FlowFuse/website/issues/1693
- [ ] https://github.com/FlowFuse/website/issues/1655
- [ ] https://github.com/FlowFuse/website/issues/1750
- [ ] https://github.com/FlowFuse/website/issues/1753
```

**Comment by Yndira-E** [comment]
Next steps: review all pages and iterate on them
