### ISSUE TITLE
Hannover Messe

### ISSUE THREAD

**Issue by Hasmin-AC** [FlowFuse/website#1792]
### Description

- [ ] Booth Backdrop graphics - [Text here](https://docs.google.com/document/d/19vlgxamNhczcls10qA59C1R4bOtff1Nuii7x5FnZ4ts/edit). Specs have been emailed.
- [ ] Create About FlowFuse Brochure
- [ ] Printable Case studies with QR code to contact us. 
- [ ] Order giveaways
