### ISSUE TITLE
FlowFuse Dedicated

### ISSUE THREAD

**Issue by MarianRaphael** [FlowFuse/website#1813]
### Description

Collection of FlowFuse Dedicated activities

What is FlowFuse Dedicated?
A single-tenant FlowFuse platform

### Scope

- FlowFuse fully manages and deploys the FlowFuse platform in a region of choice
- 30+ [AWS regions](https://docs.gitlab.com/ee/subscriptions/gitlab_dedicated/#aws-regions-not-supported) supported
- Full data and source code IP isolation
- All FlowFuse [Admin features](https://flowfuse.com/docs/admin/introduction/)
- All Enterprise Tier features included

### Next step 
- security through private networking

```[tasklist]
### Website
- [ ] https://github.com/FlowFuse/website/issues/1814
- [x] Press release: FlowFuse Dedicated
- [ ] https://github.com/FlowFuse/website/issues/1815
```

```[tasklist]
### Product
- [ ] https://github.com/FlowFuse/flowfuse/issues/3582
- [ ] https://github.com/FlowFuse/admin/issues/287
```

**Comment by ZJvandeWeg** [comment]
@MarianRaphael Can we merge this with: https://github.com/FlowFuse/flowfuse/issues/3582 ?

**Comment by joepavitt** [comment]
Just adding a link to https://github.com/FlowFuse/flowfuse/issues/4040 which is relevant here
