### ISSUE TITLE
Home, pricing and Node-RED pages review

### ISSUE THREAD

**Issue by Yndira-E** [FlowFuse/website#1932]
According to the meeting held on April 16, we're implementing these changes:

- [x]  https://github.com/FlowFuse/website/issues/1959

- [x] https://github.com/FlowFuse/website/issues/1960

- [x] https://github.com/FlowFuse/website/issues/1961

- [x] https://github.com/FlowFuse/website/issues/1962
