### ISSUE TITLE
Update meta information in core node content pages 

### ISSUE THREAD

**Issue by Hasmin-AC** [FlowFuse/website#2129]
### Description

Add specific meta descriptions, and revise titles and tags for better SEO to the following:

- [ ] https://flowfuse.com/node-red/core-nodes/
- [ ] https://flowfuse.com/node-red/core-nodes/batch/
- [ ] https://flowfuse.com/node-red/core-nodes/catch/
- [ ] https://flowfuse.com/node-red/core-nodes/change/
- [ ] https://flowfuse.com/node-red/core-nodes/comment/
- [ ] https://flowfuse.com/node-red/core-nodes/complete/
- [ ] https://flowfuse.com/node-red/core-nodes/csv/
- [ ] https://flowfuse.com/node-red/core-nodes/debug/
- [ ] https://flowfuse.com/node-red/core-nodes/delay/
- [ ] https://flowfuse.com/node-red/core-nodes/exec/
- [ ] https://flowfuse.com/node-red/core-nodes/file/
- [ ] https://flowfuse.com/node-red/core-nodes/function/
- [ ] https://flowfuse.com/node-red/core-nodes/html/
- [ ] https://flowfuse.com/node-red/core-nodes/httpin/
- [ ] https://flowfuse.com/node-red/core-nodes/httpproxy/
- [ ] https://flowfuse.com/node-red/core-nodes/httprequest/
- [ ] https://flowfuse.com/node-red/core-nodes/inject/
- [ ] https://flowfuse.com/node-red/core-nodes/json/
- [ ] https://flowfuse.com/node-red/core-nodes/link/
- [ ] https://flowfuse.com/node-red/core-nodes/mqtt/
- [ ] https://flowfuse.com/node-red/core-nodes/range/
- [ ] https://flowfuse.com/node-red/core-nodes/rbe/
- [ ] https://flowfuse.com/node-red/core-nodes/sort/
- [ ] https://flowfuse.com/node-red/core-nodes/split/
- [ ] https://flowfuse.com/node-red/core-nodes/status/
- [ ] https://flowfuse.com/node-red/core-nodes/switch/
- [ ] https://flowfuse.com/node-red/core-nodes/tcpin/
- [ ] https://flowfuse.com/node-red/core-nodes/template/
- [ ] https://flowfuse.com/node-red/core-nodes/tls/
- [ ] https://flowfuse.com/node-red/core-nodes/trigger/
- [ ] https://flowfuse.com/node-red/core-nodes/udp/
- [ ] https://flowfuse.com/node-red/core-nodes/unknown/
- [ ] https://flowfuse.com/node-red/core-nodes/watch/
- [ ] https://flowfuse.com/node-red/core-nodes/websocket/
- [ ] https://flowfuse.com/node-red/core-nodes/xml/
- [ ] https://flowfuse.com/node-red/core-nodes/yaml/

 

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by Yndira-E** [comment]
Hi @Hasmin-AC I'm currently working on a way to do this, it isn't possible at the moment because the files are generated automatically. I'll share the link to the PR here when I have it, so @sumitshinde-84 can update what's requested here.

**Comment by Yndira-E** [comment]
I did see [your comment](https://github.com/FlowFuse/website/pull/2082#issuecomment-2138162345) on the write node PR, I just wanted to solve it before replying 😉

**Comment by Hasmin-AC** [comment]
Sure @Yndira-E lets wait till its technically possible. I'm just capturing the task here so we make sure it gets done :)

**Comment by sumitshinde-84** [comment]
@Yndira-E, it's only for the docs that will go under `/node-red`, right? we can add meta elements using front matter for these docs  https://flowfuse.com/docs/, correct?

**Comment by Yndira-E** [comment]
@sumitshinde-84 It's only for the `/core-nodes`, the docs you've been writing for each node don't have a front matter, and can't have one, because all of that content is being injected to the body of those pages.

You should be able to add info to the front matter of the `/docs`.

**Comment by Yndira-E** [comment]
This is the PR: https://github.com/FlowFuse/website/pull/2130 

It's already been merged.  @sumitshinde-84, please check the description for where you need to add the information.

**Comment by Yndira-E** [comment]
Oh, and the titles are created automatically based on the name of the nodes, so no need to add that.

For instance, for the inject node the generated title is: `Node-RED - Inject Node`
